### ISSUE TITLE
Missing java dependency outside of android studio or java

### ISSUE THREAD

**Issue by liyuanmeng** [Nordgedanken/auto_hot_key_jetbrains_plugin#16]
Need to install to pycharm

**Comment by takanuva15** [comment]
Hi Liyuan, can you clarify the issue? Are you saying that the plugin is currently incompatible with PyCharm? Or is there an error during loading? (Please add a screenshot)

**Comment by liyuanmeng** [comment]
![图片](https://user-images.githubusercontent.com/11526187/85936590-e338b500-b92e-11ea-9eb5-401dea6504d1.png)

**Comment by MTRNord** [comment]
According to https://github.com/JuliaEditorSupport/julia-intellij/issues/446 this might be that we dont need to depend on it. I will need to check that.

**Comment by MTRNord** [comment]
![grafik](https://user-images.githubusercontent.com/1374914/86919993-53aeb580-c129-11ea-86fb-d0df53e03ec0.png)

Details from the Store Plugin check. Seems like there are further issues with non Idea or AndroidStudio IDEs
