### ISSUE TITLE
Thanks for this!

### ISSUE THREAD

**Issue by takanuva15** [Nordgedanken/auto_hot_key_jetbrains_plugin#2]
Hi sir,

Just wanted to say thanks for spearheading this project! I was looking for an autohotkey plugin for IntelliJ and I found yours immediately. (Otherwise I was worried I might have to make my own from scratch!)

Quick questions: 
- Do you accept contributions to this repository from outside developers?
- Can you please post a release of the plugin that works with the 2020.1.1 IDE so that I can use it ahead-of-time before it gets officially approved on the JetBrains marketplace?

**Comment by MTRNord** [comment]
Yes, any Contributions are very welcome. I myself do for the first time a Jetbrains Plugin and for the first time work with grammar files.
Funny enough Jetbrains did send me an email that they have approved the 2020.1.1 compatible version. But I guess that didn't work :)

**Comment by MTRNord** [comment]
@takanuva15 the latest release is available in the CI https://github.com/Nordgedanken/auto_hot_key_jetbrains_plugin/actions?query=workflow%3A%22Build+Plugin%22 the latest task (release 0.1.2) Is supposed to be 2020.1.1 comaptible

**Comment by MTRNord** [comment]
PS I also should note I am still learning AHK :D I started to code this before starting to learn AHK Scripts. So in both worlds, I need to learn stuff. In the world of Jetbrains Plugins as well as in the world of AHK.

**Comment by takanuva15** [comment]
Haha no worries, I just started using AutoHotkey a couple months ago as well. I released my first major script, [MenuClip](https://github.com/takanuva15/MenuClip), only a week ago on the AutoHotkey forum.

**Comment by MTRNord** [comment]
I am just at: "I have a daily script at all because I have no idea what to code with it." ^^ So very beginner level. 

PS: I am going to add some Issues about what I would like to add. Feel free to add requests or correct me on how important something is.
