### ISSUE TITLE
Can't build the project (can't find AHKTypes)

### ISSUE THREAD

**Issue by takanuva15** [Nordgedanken/auto_hot_key_jetbrains_plugin#3]
Hi, I tried cloning the repository but I'm getting an error that the `AHKTypes` class does not exist in the `AHKSyntaxHighlighter` class.

`import de.nordgedanken.auto_hotkey.psi.AHKTypes;`

I think that you may have forgotten to commit it to the repository?

(Also, can you give me some quick instructions on how to generate the zip file for the plugin?)

**Comment by MTRNord** [comment]
In theory, the runIde gradle task should generate these files. This gets generated from the bnf grammar and flex files.

**Comment by MTRNord** [comment]
Can you check if they are present after you ran the runIde task? If not I will check how to make it work :)

**Comment by takanuva15** [comment]
Ok yea, I ran `gradle runIde` and now the AHKTypes file shows as expected. I'm confused though where the plugin zip file is supposed to appear?

**Comment by MTRNord** [comment]
That one get generated with the gradle task `buildPlugin` and should be in the  `build/distributions` folder. I will add some documentation :)
